# Generated by Django 3.1.6 on 2021-02-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20210207_0028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfileModel',
            new_name='UserProfile',
        ),
    ]
