# Generated by Django 3.1.6 on 2021-02-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='organization',
            new_name='organisation',
        ),
    ]
